branch-defaults:
  master:
    environment: myapp
  develop:
    environment: myapp-staging
global:
  application_name: myapp
  default_ec2_keyname: damien-keypair
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Ruby 2.3 (Passenger Standalone)
  default_region: us-east-1
  sc: git