machine:
  python:
    version: 2.7.6

dependencies:
  pre:
    - pip install awsebcli
    - printenv

database:
  override:
    - exit 0

test:
  override:
    - exit 0

deployment:
  staging:
    branch: staging
    commands:
      - eb deploy vegewel-staging
  production:
    branch: master
    commands:
      - eb deploy vegewel